### ISSUE TITLE
Make the algniment justified in the articles

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/docs#152]
currently, articles are left aligned

![image](https://user-images.githubusercontent.com/32236948/97812197-00d0af00-1c80-11eb-937c-0151152c0bd7.png)

I guess that's what is causing the weird behavior with the code span ("hopefully", rather... :/ )

Anyway, justified alignment improve the overall aspect of the page and ease the reading, allowing to identify more easily the different §, hence the different ideas.

**Comment by kazk** [comment]
Unfortunately, text align won't fix this.

`text-align: left` (default)
![image](https://user-images.githubusercontent.com/639336/97932221-56f72e00-1d24-11eb-969d-8045b5f17fad.png)

`text-align: justify`
![image](https://user-images.githubusercontent.com/639336/97932187-4050d700-1d24-11eb-8bde-82864ab02c41.png)

**Comment by hobovsky** [comment]
Even if so, can we still have it? Do you like lwfr aligned, or justified text more?

**Comment by kazk** [comment]
I found a fix for the weird wrapping.

Left:
![image](https://user-images.githubusercontent.com/639336/97933701-5cef0e00-1d28-11eb-94f4-8092ee7d2c83.png)

Justify:

![image](https://user-images.githubusercontent.com/639336/97933670-40eb6c80-1d28-11eb-8bcf-02fb68716e03.png)

I think justified text looks good and readable only when it's adjusted well and long words are hyphenated. Otherwise, you'll often get huge spaces in between words. In our case, we can't hyphenate the thing that's causing line break because it's not a word, but a span of code. Aligned left won't have huge space in between text at least.
I haven't found any positive articles about justified text on web.

**Comment by hobovsky** [comment]
Then lets keep it this way.
Having this broken span thing fixed is nice enough 👍
