### ISSUE TITLE
Improvements to the authoring guidelines (Writing a Reference Solution)

### ISSUE THREAD

**Issue by FArekkusu** [codewars/docs#177]
[Link to the article](https://docs.codewars.com/authoring/guidelines/reference-solution/).

> Sometimes maintainers and translators are not sure what the author's original intention behind the kata was in terms of its difficulty, edge cases and additional restrictions. The reference solution of the initial language version can then be used as a baseline for other translations.

This part is not really good as the author might write a bad reference solution, and using it as baseline for translations would be just as bad. I think it'd be better if the part about "the translators being unsure" and "the solution acting as a baseline" was not included at all because it's more related to the kata itself, and not whatever code the author decided to use as the reference.

> The reference solution of a translation should not be significantly better or worse than the original one.

I don't really understand why this part is even present. Different languages have different performance, different built-in features, different libraries available on CW, different compiler flags - the translation should *do the same thing*, and not *work in the same way*.

Speaking of non-performance-oriented katas, if the reference solution is much worse, then, of course, it'd be annoying to wait ages on every attempt, or run into out-of-memory issues, but I don't see any reason why a better reference solution would be bad.

Speaking of performance-oriented katas:
* if the same approach yields better performance in some particular language, then tests should be adjusted accordingly
* if it is not possible to achieve the same performance, then it might be better to not write a translation at all

___

Also, it'd be good if there was a point that authors should aim for good performance of their reference solutions in general to avoid situations where users have to wait ages for tests to complete only because the author's solution is hundreds of times slower than their code.

**Comment by hobovsky** [comment]
> Also, it'd be good if there was a point that authors should aim for good performance of their reference solutions in general to avoid situations where users have to wait ages for tests to complete only because the author's solution is hundreds of times slower than their code.

This page is not about reference solutions used by tests, but about the code snippet with initial solution of the author/translator. It's true that naming is ambiguous here (both things are called "reference solution"), and initially I used separate terms for these, but it did not catch. So if you'd have a good idea how to differentiate between "author's solution" snippet and "reference solution" used by tests to produce expected values, I am all ears.

That being said, the reference solution won't cause tests to take long, because it's not being run at that time. Tests are allowed to use another, more efficient implementation (what is mentioned by "submission tests" page).

**Comment by Blind4Basics** [comment]
And why not just those two expressions? :o 
* "author's solution" 
* "reference solution"

**Comment by hobovsky** [comment]
Because [you have not shared this idea before](https://github.com/codewars/docs/issues/154), so I went with what was proposed :)

**Comment by Blind4Basics** [comment]
well, it's your idea, actually x) 
;)

**Comment by FArekkusu** [comment]
> This page is not about reference solutions used by tests, but about the code snippet with initial solution of the author/translator

Then I don't understand why this page exists at all. Who cares what the author's using as his "submitted solution"? When writing a translation only the preloaded code, sample tests, and fixture matter.

**Comment by hobovsky** [comment]
I somewhat disagree with this point of view and I will try to explain why.

It happens quite often that when translators create a new translation of the kata, they change it significantly with regard to some details, for example:
 - original version allows O(n!) solutions, and translation rejects anything more complex than O(n^2), or vice versa
 - For "matrix addition" kata, original version requires addition to be performed in place, and translation performs operation of copy and add,
 - original version requires handling of some edge cases and exceptional inputs or performs some validation, and translation does not handle such cases

First problem is that such discrepancies appear at all, while they should not. All language versions of a kata should be similar in such aspects. Havingadditional guideline in form of reference solution might prevent it.

The other problem is that when such differences occur, reviewers raise issues that kata is inconsistent, and translators reply that no one knows what authors meant. I thought that it would be good idea to add to this particular snippet some additional meaning (i.e. make it not useless anymore), so it carries the idea of the kata better. In most cases such situations should not occur, because everything should be clearly specified in the description, and this snippet should conform to this description, so indeed it would not be that meaningful. But since sometimes descriptions are what they are, "reference solution" could serve as some kind of reference, or a medium to resolve ambiguities if something were underspecified in the description, or could not be easily described at all, etc.

**Comment by FArekkusu** [comment]
Author's submitted solution is a piece of code which just so happens to pass the tests, it doesn't have any special meaning, and shouldn't have one. It may deliberately ignore some of the kata requirements if the author knows that the language itself will handle those (i.e. some operation will throw an exception without requiring the author to do some explicit checks), or include code that is not required at all (I've seen some kata author add input validation in their submitted and reference solution even though invalid inputs were never tested).

All those discrepancies you mentioned are a problem with tests, and have nothing to do with whatever the author submits for others to see.

**Comment by hobovsky** [comment]
So if I am getting you right, this snippet is just a solution as every other submitted by any other user and it should not be a subject of any requirements related to authored content? Are there any requirements you'd put on it? Would you accept this snippet if author golfer it or obfuscated just for lulz?

**Comment by FArekkusu** [comment]
> this snippet is just a solution as every other submitted by any other user and it should not be a subject of any requirements related to authored content?

Yes.

> Are there any requirements you'd put on it?

No.

> Would you accept this snippet if author golfer it or obfuscated just for lulz?

Yes.

**Comment by hobovsky** [comment]
Okay, I think I mostly agree with you and it seems that I just wanted to (unnecessarily) add some meaning  so something what maybe is not meaningful that much. Almost all things I wanted to use it for should be handled by other parts of the kata, mostly by description and test suite. There's one thing I would like to keep though, and I'd appreciate if you pointed out to me why I am wrong:

I would still keep a requirement for the reference solution to conform (in some extent) to general coding guidelines (this page is still work in progress, but general idea can be seen [here](https://deploy-preview-173--reverent-edison-2864ea.netlify.app/authoring/guidelines/coding/)), which, more or less, translate to "try to make your code to be easy to maintain by others".

"Reference solution" snippet is used when a kata or translation is republished, and every maintainer _can_ encounter problems which could be avoided if author followed some rules. I imagine it can be somewhat annoying when someone updates a kata (for example fixes a bug in tests) and suddenly it cannot be published because reference solution does not work anymore. And I do not mean situations when it stops working because of some change in the environment which was expected to be incompatible - in such situations it's ok. I mean situations when some _backwards compatible_ change occurred, some time later the kata is edited and cannot be easily republished anymore, and this situation is caused solely by author's disregard for any rules and could be avoided.

For example, author did not put some required `#include` in their solution, kata got accepted, and after some time a maintainer wants to republish it and it turns out that this snippet does not compile anymore. Is it a problem, or not? Is it original author's fault or not?

What I generally mean is that reference solution is not "write once and never use again", because it's (potentially indirectly) used by maintainers and can incur some additional maintenance cost due to carelessness of the author.

What do you think?

**Comment by FArekkusu** [comment]
> I do not mean situations when it stops working because of some change in the environment which was expected to be incompatible

> author did not put some required `#include` in their solution...

If something stopped working because of a lacking `#include` that would be caused by a change in the environnent, no?

This is kind of gray area, and idk what to do about this. I don't see why there should be any requirements imposed on the complete solutions, apart from the fact that it cannot be a cheat. The only situation where asking the translator to write a good complete solution would make sense is when the translation is written for a language where breaking platform-dependent changes are possible, like C++ with its horrendous `include` system and headers being concatenated to files on CW (C++ could very well be the only such exception on CW). Otherwise, the complete solution can't break out of the blue. If it stops working, then the fixture *which was written in pair with that solution* is most likely broken as well - you will never need to fix **only** the complete solution.

I think you could leave it as a suggestion: "don't write a crappy complete solution", but nothing more than that.

**Comment by hobovsky** [comment]
The page was simplified, most of remarks present here were addressed.

Thanks @FArekkusu for your input!
