### ISSUE TITLE
Improve styling of remark containers

### ISSUE THREAD

**Issue by hobovsky** [codewars/docs#180]
I think that default styles provided by the plugin are somewhat counter-intuitive. 

`note` is very obtrusive:
![image](https://user-images.githubusercontent.com/23709795/100394828-d4217480-303e-11eb-86ec-ea355b1e7cbb.png)

 `important` is much milder and, IMO, not as expressive as it should:
![image](https://user-images.githubusercontent.com/23709795/100394844-e1d6fa00-303e-11eb-875b-de717e92490f.png)

I'd expect these two to be opposite. Do you think it would be OK to switch these two: make `note` blue (as "it's just an information"), and make `important` to stand out prominently?

Icons used by them are OK, I just do not like the colors.

**Comment by kazk** [comment]
`important` was an alias of `information`, so that's why it's styled that way. I think the types were too ambiguous and icons were too similar, so I decided to define our own.

`note`, `tip`, `info`, `warning`, `caution` (should be rare to use, need a better name).

![image](https://user-images.githubusercontent.com/639336/100420792-e948d400-303b-11eb-9383-b9a8764dbf1d.png)

![image](https://user-images.githubusercontent.com/639336/100420849-05e50c00-303c-11eb-8f89-7675a6d04447.png)

Note that I'm updating the CSS framework and the color palette as well. The current dark theme is too greenish.
