### ISSUE TITLE
Migrate "Clans, Allies & Followers" from old wiki

### ISSUE THREAD

**Issue by hobovsky** [codewars/docs#201]
Breakdown of #5 

Describe concepts of Clans, Allies & Followers, possibly reusing content from [old wiki](https://github.com/Codewars/codewars.com/wiki/Clans,-Allies-&-Followers).

**Comment by hobovsky** [comment]
@kazk Do you think it's ok w.r.t. placement and organization? I am not sure if it's worth having separate HOWTOs on joining or leaving a clan, but maybe you think it is?

I wanted to add screenshots of allies/followers/following boards, I am just not sure if it's ok to put screenshots from my board (potentially anonymized, blurred, etc), or should I somehow create some "neutral" boards with some generic/fake data?

**Comment by kazk** [comment]
I think it's fine.

> I am not sure if it's worth having separate HOWTOs on joining or leaving a clan, but maybe you think it is?

What you already have looks enough to me.

Clan is another WTF of Codewars. There's no such thing. It's just a free text field that makes users with the same text follow each other. Nothing more.

This is why you get more and more allies as you change your clan field. Previous clan members are not removed automatically because there's no difference from users you had followed manually.

I've been wanting to deprecate it and support proper team/org, but it's not a high priority.

> I wanted to add screenshots of allies/followers/following boards, I am just not sure if it's ok to put screenshots from my board (potentially anonymized, blurred, etc), 

I think using yours is fine without anonymizing. It's public information.

**Comment by hobovsky** [comment]
Yeah I decided to migrate this part because I considered it somewhat of a low hanging fruit, and questions about clans pop up from time to time.

I will try to get some screenshots then and see how they turn out.
