### ISSUE TITLE
Writing Submission Tests

### ISSUE THREAD

**Issue by JohanWiltink** [codewars/docs#233]
My apologies for not working within the framework, with Pull Requests and other things I don't understand.

My suggestions on the "Writing Submission Tests" document:

# Reference Solution

I would like for a clear distinction to be made between Example solution and Reference solution. They _don't_ have to be the same, and they have very different roles. The Example solution would be the solution shown as the author's solution, and it should be first and foremost readable. Also, if a kata has a pointe, the Example solution should make it. The Reference solution is used to test solver answers against, and should first and foremost be fast. Maintainability is good, but IMO not at the expense of speed ( as perceived by a human - don't go shaving off microseconds at the expense of maintainability ). Having different implementations for them is actually a good thing, because it reduces the chance of bugs in the kata, finds more edge cases &c. It's not difficult to test your reference solution against any fixed tests either - you can disable those for the production kata.

# Random Tests

> The goal of random tests is to make the inputs unpredictable ..

No. "The goal of random tests is to make the _expected results_ unpredictable  .." Sometimes, randomising the inputs is not enough for that.

# Performance Tests

I would like to see a little more technical explanation of the why and the how of performance testing. Too often authors, even experienced ones, think stress testing a solution simply means running tests for 9 seconds. If you're testing for `O(n)` as opposed to `O(n^2)`, testing can succeed in milliseconds for a compliant solution, and consistently time out for an uncompliant one, if your ( few ) inputs are big enough ( but not too big, obviously ).

Also, a warning against micro-optimisations would be useful to have in there.

# Missing section

This maybe in another document already. If so, a pointer can be included with a very short section.

_Tests should not test process. Tests should test outcomes._

This follows from what a kata should and should not be. A kata should define a transformation by inputs and outputs only. If a solver can design an alternative transformation, that should be OK. There obviously are exceptions to this, and sometimes you describe or specify a transformation as a process, in toto or up to a point, but the general rule stands. It's a destination, not a journey. ( As mentioned, there are exceptions to every rule! )

This general guideline can occasionally be helpful in deciding what and how to test. It might even be helpful in designing the kata itself - what can I, what can't I test?

**Comment by hobovsky** [comment]
> My apologies for not working within the framework, with Pull Requests and other things I don't understand.
> 
> My suggestions on the "Writing Submission Tests" document:

Don't worry about the process, and thank you for your feedback. You are one of a very few users outside of the docs team who bothered to give any feedback, and it's very valuable to us. Seeing you as a keen reviewer I hope you would find the guidelines  useful for driving users through the beta process and use them to point out potential issues to the authors. That's what they were created for.

Regarding your remarks, I will address them in a post below some time soon. Some of your points had already been considered and rejected, some were proposed and did not catch, and some I just did not know how to put into words.

To discuss some opinions and points of view, I generally prefer more direct contact than forum, and I would like to ask you if it were OK for you if I got to you directly on gitter, to, for example, ask some follow up questions. But if you prefer discussion via the board here, it's also OK.

If you want, I can also guide you through the most necessary GitHub functions so you would be able to propose changes yourself, if you want ;)

Thanks!

**Comment by JohanWiltink** [comment]
If Gitter works better for you, Gitter is fine. I get mail notifications for that, so I should not miss anything.

I'm not sure I want to propose changes. I'm not sure I actually want to write text myself. Also, sometimes I'm on a recent Debian but sometimes I'm on Windows XP, and I don't really want to install new things on the XP box ( if they can still be found ) and I often don't even know _how_ to install things on the Debian boxes. ( I do most of my coding right in CodeWars. ) I :heart: web interfaces, especially if they run in Firefox 52 on Windows XP.

**Comment by hobovsky** [comment]
Ad "Reference solution":

Naming has been discussed here: #154 but the topic did not catch too much traction. I hate to have two things named "reference solution" because it's confusing and I will be glad to rename one of them and use two distinctive names through the docs. The issue is still open, so you can post your suggestions there.

> I would like for a clear distinction to be made between Example solution and Reference solution. They _don't_ have to be the same, and they have very different roles.

Agreed, and I thought there is a note on it, but I cannot find it now. I initially also had an idea of giving a more significant role to the author's solution (see [this change](https://github.com/codewars/docs/commit/df95d8b7307d03e2585e5c80f2fe6b1fb71ed21f#diff-f78c2194775ea2c7a7890f12abf634914dd1ffb4c52386df92b193a08b21c824)), but I think I went too far and wanted to make it _too_ significant. After discussion with FArekkusu (see #177) it was simplified, and maybe it was simplified too much. There's a bit of disagreement here and I've already heard three opinions of what the "author's solution" should and should not be.

The other thing is that I would like to suggest somehow that neither the reference solution (if used), nor author's solution, should not stand out _too much from approvable solutions_, because it could, in some cases, serve as spoiler. In most cases I do not care about it being orders of magnitudes better than acceptable user solutions, but I would like to somehow suggest that it should not reveal solution to "tiered" kata. I need to think about some wording here and how to describe it, and if you have any ideas, just PM me on Gitter.

EDIT: yay, just found the note I was sure I put there, but could not find :D It states as follows:

> The reference solution, if used, does not have to be the same as the one in the "Reference Solution" snippet. [...]

and is placed in... "Performance tests" section 🤷‍♂️  . I think it's misplaced and I will move it to "Reference solution" paragraph of the same page.

----

Ad "Random Tests":

> No. "The goal of random tests is to make the _expected results_ unpredictable .." Sometimes, randomising the inputs is not enough for that.

I think it's a matter of wording, I will think how to improve it.

----

Ad "Performance tests":

> I would like to see a little more technical explanation of the why and the how of performance testing. 

I have some doubts here, but I will think of something. I simply think it's not that easy.

> Too often authors, even experienced ones, think stress testing a solution simply means running tests for 9 seconds. If you're testing for `O(n)` as opposed to `O(n^2)`, testing can succeed in milliseconds for a compliant solution, and consistently time out for an uncompliant one, if your ( few ) inputs are big enough ( but not too big, obviously ).

There's a couple of points which I hoped cover this (damn, we really need these linkable bullet points):

> [...] better to have a few tests with large input rather than many with medium-sized inputs. [...]
>
> [...] The difference between accepted and rejected solutions should be easy to spot. [...]
>
> [...] The test suite should not take a long time to run.[...] - (addresses the point somewhat indirectly)

I specifically avoided mentioning complexities and big-O stuff here, because I was afraid to write something stupid, and because I think it not always applies. I think that there are kata which differentiate between performant and slow solutions of the same complexity class. For example, kata which can be solved with DFS or BFS but Intentionally) rely on some smart, efficient, aggressive pruning of the search branches. 


> Also, a warning against micro-optimisations would be useful to have in there.

Agreed, will think of something.

----

Ad "Missing section"

> _Tests should not test process. Tests should test outcomes._

Good point.

----

Maybe some of your points are already there, but misplaced or not stressed sufficiently. Some points I will definitely add, thanks for suggestions.

If you'd like to discuss something, I generally prefer Gitter, because discussion via chat is much more effective than via forum, so just PM me if you have any questions.

Thanks!

**Comment by hobovsky** [comment]
Reverence solution vs example solution is discussed in #154.
Follow-up task for HOWTO on performance tests is here: #241.

Remaining remarks were addressed and added to the doc, so I think this one can be closed.

Thanks for feedback!
