### ISSUE TITLE
Error in JavaScript: creating and translating a kata # Reference solution

### ISSUE THREAD

**Issue by JohanWiltink** [codewars/docs#260]
[JavaScript: creating and translating a kata # Reference solution](https://docs.codewars.com/languages/javascript/authoring/#reference-solution) states

> The reference solution or data _**must not**_ be defined in the top-level scope of the test suite or in the Preloaded code.

For JavaScript, this is incorrect. The tests run in their own scope, which is a subscope of the one where the solution runs, and it does not leak any definitions.

Because [Writing Submission Tests # Reference solution](https://docs.codewars.com/authoring/guidelines/submission-tests/#reference-solution) warns explicitly that "The reference solution should be completely inaccessible outside the submit tests", the article should specify that any test code is, in fact, inaccessible to the solution, and any place in the test suite, including the top level, is appropriate to put your reference solution.

Article "Writing Submission Tests" refers to language reference pages, which may be applicable for other languages, but for JS that page does not include any information on this matter. Should that be a separate issue? Should the JS language reference page have this information, or should the link be changed? ( The JS reference page does include a link to the "JavaScript: creating and translating a kata" article, but it is not clear that is where to find the relevant information if you just followed the link. )

**Comment by hobovsky** [comment]
Thanks for reviewing, and for spotting this issue.

I am not a JS person, so I am totally unfamiliar with mechanisms used by Node, or with the way solutions and tests are prepared and run by the CW runner. I have also no idea what are "run scopes" you mention :( 

I think the reference solution used to be accessible when JS snippets were concatenated, but it's not anymore for Node 12 setup. If I am right, authors would have to ensure that the kata is not available in versions of node prior to 12.

_**"Writing Submission Tests # Reference solution"**_ should probably be more explicit about the fact that the issues affects only some set of languages. The _**"JavaScript: creating and translating a kata # Reference solution"**_ should probably also contain a small paragraph that JS is not affected. It might seem a bit redundant (why describe something what's not there?) but maybe it would clear up some doubts (it would for me).

I can fix bot articles, but first someone would have to explain me in a bit more of details what exactly makes top-level functions in JS tests inaccessible. Is it because of modules? Or something else?

**Comment by JohanWiltink** [comment]
> the reference solution used to be accessible

You are not right. All supported JS versions make the test suite completely inaccessible from the user solution.

**Comment by JohanWiltink** [comment]
Preloaded and user solution are concatenated. Test suite is then concatenated in an IIFE. The whole concatenation is run and returns the result of the test suite. I should not be the person explaining this to you; @kazk or someone similarly actually versed in what actually happens should be. I'm parroting what I've read somewhere and is consistent with what I see happening - but I can't actually look at it and I can't actually support it.

**Comment by hobovsky** [comment]
I had to look up IIFE, but it all makes sense now. So everything is concatenated in a such way so contents of the test suite are non-global and non-public. That's good to know, thanks for explaining. I will think how to apply this information to mentioned articles.

> I should not be the person explaining this to you; @kazk or someone similarly actually versed in what actually happens should be.

There's #70 for this.

**Comment by kazk** [comment]
Node v12 concatenates like this:

```javascript
// preloaded code if present
// solution code

;(function() {
// tests code
})();
```
Node v10 has `const Test = require("cw-2");` prepended.

Node v8 uses the old custom test framework, so there's an extra wrapper, but same idea.

---

I'd like to _eventually_ switch to proper modules. For supporting existing contents, there are tools to process legacy code to export global identifiers.

**Comment by hobovsky** [comment]
@JohanWiltink could you please see #263 if it's better now.
