### ISSUE TITLE
Docs home page: organization?

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/docs#46]
To get a better idea about how the thing will eventually work:

## Currently:

![image](https://user-images.githubusercontent.com/32236948/87406705-5d209d80-c5c1-11ea-9af7-aaaa87b7e3e9.png)

## Suggestions/questions:

So, I guess every "entry point" for documentation will land as an icon in the bottom part of the screen. This leads to some questions:

### 1) how are they organized?
reading through https://github.com/codewars/docs/blob/master/src/pages/Index.vue, it seems they are automatically displayed in the order the components are inserted into this file (`g-link` parts). Right?

### 2) is it possible to visually separate them?

Like, to have line separations or something  in the home page to split some icons from others?

### 3) when more things will be there, what general organization should we use?

On this, and if the previous point is possible, I'd see the following:
- first icons: glossary/category/tags/supported languages (on the same line if possible)
- an horizontal line
- all other topics by alphabetial order

### 4) what other topics?

Here is the critical point, imo. 'Time to define some ways of splitting the docs so that we can have a better idea about where we are going.

I'd go for the followings (in random order and non exhaustive, ofc), the idea being that those categories could contain sub parts possibly used at several different places:

* getting started (not sure if it's good to have it doubled with the link in the center of the page but...). See #40 

* codewars general informations, that would roughly be filled with :
  - https://github.com/codewars/codewars.com/wiki/About-Codewars
  - https://github.com/codewars/codewars.com/wiki/Kata
  - https://github.com/Codewars/codewars.com/wiki/Honor-&-Ranks (more detailed version of what would be in the "getting started/finding-kata.md" part
  - https://github.com/codewars/codewars.com/wiki/Community-Code-of-Conduct
  - ...

* codewars UI (detailed/exhaustive version of what I suggested to add to the "getting started" part. Not entirely sure it deserves a specific topic, tho)
  - ...

* beta process
  - ...

* kata authoring and translating
(I put the info there otherwise it could be lost in zulip at some point: `authoring tutorial: give credit to the original source when needed`)

* Codewars' users
  - regular/red users
  - moderaotrs/team/admins (assuming "moderators" become something different from PUs)
  - power users
  - link again to the code of conduct
  - privileges
  - Social aspects (clans, followers, ...)
  - ...

* tutorials (possibly linking other parts in the previous sections). 
  - markdowns
  - troubleshooting
  - create tests/snippets(?)
  - the "getting started" tutorial should be present there again (might be a better idea than to put is as an icon in the home page)
  - how to debug your solution using the console
  - ...

* Maybe a FAQ section would be a good addition. That would only be another way for the users to go/access to informations spreaded in other places (idea comming from @Steffan153 's [post on zulip](https://codewars.zulipchat.com/#narrow/stream/244904-docs/topic/memo.20-.20various.20docs/near/203347662) )

---

Here are my 2 cents...

@kazk: is that in your line of thougths for the docs?

---

Some other ideas randomly stored [there](https://codewars.zulipchat.com/#narrow/stream/244904-docs/topic/memo.20-.20various.20docs)

**Comment by hobovsky** [comment]
My idea:

Main page can be as empty as possible, with a couple of ways to search for eventually interesting articles:
 - **Getting started** for ones not knowing how to start,
 - **Glossary** for people hunting for some specific thing - this makes important that entries in glossary have some links to doc area which documents topic of the term in details
 - **Categories** as a kind of coarse ToC with additional benefit of more than one direction cutting through the set of articles
 - **Tags** as finer grained search

What you described makes IMO good candidates for Categories, so for example an article about kata trainer could be placed in both **Solving** and **GUI**. Generally I think that **GUI** is not even a good category, because... who'd need a reference to "whole" GUI in one place? Main direction docs are laid out IMO should be functions and activities.

Going this way, I would make *Tutorials* and *FAQs* a category. The question is, if they will stand out prominently enough to be easy to find by people searching for help.

But this idea has a problem that I do not know if categories list can be composed in some nice way, or is it just a blob of links. If we could have some nice thumbnails etc. it would be great. But I do not know what's possible with our docs system, I didn't get too familiar with it, yet :(

**Comment by Blind4Basics** [comment]
About the functionnality aspects, I agree with you. But, thing is, this way, you push the accessibility of the info one link further (even if these categories/tags/... things can be made something else that the blob of links) and most users won't like the idea to do that extra click.

But you're right about keeping the number of icons as little as possible, to increase readability.

**Comment by hobovsky** [comment]
I agree that it unfortunately brings things one click further, but maybe we could save/hint them this one additional click:

![image](https://user-images.githubusercontent.com/23709795/87417002-d32c0100-c5cf-11ea-9122-897048e6b3db.png)

**Comment by Blind4Basics** [comment]
not really found of the idea...

Another one, keeping the "one click further" thing, but allowing to have a complete/detailed page: just add one item **Table of contents** and set up what I suggested in that page?

**Comment by kazk** [comment]
`category` was a bad name to organize documents by type (#8). I was thinking something like this:

![image](https://user-images.githubusercontent.com/639336/87465370-601f8c00-c5c9-11ea-9c53-aac63e09a815.png)

I'll rename `category` to `type` (or `doc_type`) and add `topic` to classify by the main subject.

---

@Blind4Basics 

> 1) how are they organized?

Not sure if I'm understanding your question, but the code for those 4 links are here:
https://github.com/codewars/docs/blob/cbbd483458b0212c3a9ac4a3611b6eea10c9830c/src/pages/Index.vue#L32-L80

As I said before, we're going to iterate on this and optimize as we go.

> 2) is it possible to visually separate them?
> Like, to have line separations or something in the home page to split some icons from others?

That's possible. We can change any styles.

> 3) when more things will be there, what general organization should we use?

I wasn't planning to add too much on the landing. The search will be super useful once we switch to DocSearch (#4) too.

@hobovsky 

> But this idea has a problem that I do not know if categories list can be composed in some nice way, or is it just a blob of links. If we could have some nice thumbnails etc. it would be great. But I do not know what's possible with our docs system, I didn't get too familiar with it, yet :(

Pretty much anything is possible because this is fully customizable (just a Vue app).

I wasn't going to focus too much on organizing and styling yet until we have more docs, but we can start discussing it or consider start doing some of them.

**Comment by hobovsky** [comment]
>  I was thinking something like this: [picture]

That's exactly what I thought categories to be, I was just wondering about presentation , if we could get such tiles or something. If we can, then great!

**Comment by Blind4Basics** [comment]
> 1) how are they organized?

I was just talking about their order. But since it's fully customizable, "whatever".

Topic/categories: looks great, in that case, yeah.
Though, I still think a full "table of content" somewhere would be useful to some users.

**Comment by kazk** [comment]
@Blind4Basics Can you elaborate on full table of contents? Is it a list of all pages and links to them? We should be able to generate one from the data.

**Comment by Blind4Basics** [comment]
yes something like that, but with formatting, sections, and mostly a wanted order (just like in a book).

It's surely doable automatically, yes, but I'mp not sure it's that easy to do. Maybe by adding an index to each main page/topic, then study the graph dependency, yes. But cycles will happen at some point... => ?

**Comment by kazk** [comment]
Yeah, we should be able to do that dynamically by storing some information for ordering within the page data (or infer from `prev`/`next` links). Topic and Type can be declared in the desired order and sort by that.

1. Get all `pages` grouped by `topic` and sort the groups by `topic`
2. For each group, group pages by `type` and sort the groups by `type`
3. For each subgroup, sort the pages by some information (some extra field or links)

Another way is to have something statically defined like the sidebar:

https://github.com/codewars/docs/blob/319c2197afa3b93134bb7013f494f022e8554fae/gridsome.config.js#L23-L41

This is simple and pretty flexible about what to include and how to order, but can be annoying to keep updating. This is why I added a way to automatically generate a sidebar for pages related to the language with `sidebar: "language:id"`.

Anyways, we can do whatever that fits our needs and I think we should wait until we have more docs to understand what's best.

**Comment by kazk** [comment]
The landing looks like this now:

![image](https://user-images.githubusercontent.com/639336/87499139-50766680-c60e-11ea-8f6c-b1e5bcabb165.png)

Let's open a new issue for topics if you'd like to start collecting them.

For documentation kinds, let's continue at #8.
