### ISSUE TITLE
Finish the Markdown reference/tutorial

### ISSUE THREAD

**Issue by kazk** [codewars/docs#67]
* [x] markdown home page
* [x] extensions page (reference)
* [ ] some sort of tutorial, but where/in what section? (see [message below](https://github.com/codewars/docs/issues/67#issuecomment-667889084))

---

#62 added a stub page for basic Markdown syntax and we need to complete it. The page should be minimal and easy to scan. Any nonstandard Markdown features were extracted into a separate page.

Basic Markdown that most users use is extremely simple and should focus on that. For example, GitHub's Markdown Cheat Sheet looks like this:
![image](https://user-images.githubusercontent.com/639336/87829833-a75d8500-c834-11ea-9c0f-5023c48ca3ce.png)

Include the syntax for:

- Emphasis
- Code Block
- Lists
- Links
- Blockquotes

I'm not sure if it's worth including the result. For most of them, it'll look very similar to the original syntax and it's pretty obvious. It can look slightly different on Codewars because different libraries are used and CSS is different. For Headers, it'll also mess with the table of contents as well.

**Comment by Blind4Basics** [comment]
about the math part: https://github.com/codewars/codewars.com/issues/1527

**Comment by Blind4Basics** [comment]
I'm planning on doing the extensions page as a reference, so I'll prune it from some tiny parts (for now I'll keep them commented out for later).

Thing is, I'd like to create a tutorial about markdown, but I'm not sure how to tackle it, since it can be usefull for creating kata (description) as well as for comments.
Hence, simpler course of action should be, I guess, to make it a stand alone thing, but I feel it a bit weird at the same time. Any thoughts? (Maybe I'll just give it a shot in some time and we'll see after that?)

**Comment by Blind4Basics** [comment]
Up here! To see if we close this one or not.

* Do you (plural) think we need a tutorial or recipe about markdowns yet?
* If so, do we make it a stand alone thing, or do we rather incorporate it to something else (like, `writing descriptions`)?

**Comment by kazk** [comment]
Not really for Markdown itself, but I think we should have something for "how to write comments effectively" and also "how to write kata descriptions". For kata description, we should have some recommended style (what to include, how to structure, etc).

**Comment by Blind4Basics** [comment]
ok, I'll open a temporary "todo" issue to kee track of this.

:+1:
